name: Beacons
version: '${project.version}'
main: luke.beacons.BeaconRange
api-version: 1.19
authors: [Galaticbiohazard]
commands:
  BeaconRange:
    description: The plugin to change your beacon range.
